--
-- PostgreSQL database dump
--


-- Dumped from database version 16.15 (Homebrew)
-- Dumped by pg_dump version 16.15 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: app_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_user (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    display_name character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    bio character varying(280)
);


--
-- Name: app_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contest_problem; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contest_problem (
    id bigint NOT NULL,
    order_index integer NOT NULL,
    solved_at timestamp(6) with time zone,
    contest_session_id bigint NOT NULL,
    problem_id bigint NOT NULL
);


--
-- Name: contest_problem_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.contest_problem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contest_problem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contest_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contest_session (
    id bigint NOT NULL,
    difficulty character varying(255),
    duration_minutes integer NOT NULL,
    finished_at timestamp(6) with time zone,
    sheet_slug character varying(255),
    started_at timestamp(6) with time zone NOT NULL,
    status character varying(255),
    user_id bigint NOT NULL,
    CONSTRAINT contest_session_difficulty_check CHECK (((difficulty)::text = ANY ((ARRAY['EASY'::character varying, 'MEDIUM'::character varying, 'HARD'::character varying])::text[]))),
    CONSTRAINT contest_session_status_check CHECK (((status)::text = ANY ((ARRAY['IN_PROGRESS'::character varying, 'FINISHED'::character varying, 'ABANDONED'::character varying])::text[])))
);


--
-- Name: contest_session_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.contest_session ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contest_session_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: problem; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.problem (
    id bigint NOT NULL,
    difficulty character varying(255),
    external_url character varying(255),
    order_index integer NOT NULL,
    title character varying(255),
    topic_id bigint,
    statement character varying(1000),
    space_complexity character varying(255),
    time_complexity character varying(255),
    example_input character varying(500),
    example_output character varying(500),
    editorial_url character varying(255),
    video_url character varying(255),
    CONSTRAINT problem_difficulty_check CHECK (((difficulty)::text = ANY ((ARRAY['EASY'::character varying, 'MEDIUM'::character varying, 'HARD'::character varying])::text[])))
);


--
-- Name: problem_constraints; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.problem_constraints (
    problem_id bigint NOT NULL,
    constraint_text character varying(500),
    constraint_order integer NOT NULL,
    CONSTRAINT problem_constraints_constraint_order_check CHECK ((constraint_order >= 0))
);


--
-- Name: problem_examples; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.problem_examples (
    problem_id bigint NOT NULL,
    explanation character varying(1000),
    input character varying(1000),
    output character varying(1000),
    example_order integer NOT NULL,
    CONSTRAINT problem_examples_example_order_check CHECK ((example_order >= 0))
);


--
-- Name: problem_hints; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.problem_hints (
    problem_id bigint NOT NULL,
    hint_text character varying(1000),
    hint_order integer NOT NULL,
    CONSTRAINT problem_hints_hint_order_check CHECK ((hint_order >= 0))
);


--
-- Name: problem_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.problem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.problem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: problem_tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.problem_tags (
    problem_id bigint NOT NULL,
    tag character varying(255)
);


--
-- Name: sheet; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sheet (
    id bigint NOT NULL,
    description character varying(500),
    name character varying(255) NOT NULL,
    order_index integer NOT NULL,
    slug character varying(255) NOT NULL
);


--
-- Name: sheet_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sheet ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sheet_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: submission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.submission (
    id bigint NOT NULL,
    code oid,
    language character varying(255),
    passed_count integer NOT NULL,
    runtime_ms bigint NOT NULL,
    submitted_at timestamp(6) with time zone NOT NULL,
    total_count integer NOT NULL,
    verdict character varying(255),
    problem_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT submission_language_check CHECK (((language)::text = ANY ((ARRAY['JAVA'::character varying, 'PYTHON'::character varying, 'JAVASCRIPT'::character varying, 'CPP'::character varying])::text[]))),
    CONSTRAINT submission_verdict_check CHECK (((verdict)::text = ANY ((ARRAY['ACCEPTED'::character varying, 'WRONG_ANSWER'::character varying, 'RUNTIME_ERROR'::character varying, 'COMPILE_ERROR'::character varying, 'TIME_LIMIT_EXCEEDED'::character varying])::text[])))
);


--
-- Name: submission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.submission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.submission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: test_case; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.test_case (
    id bigint NOT NULL,
    expected_output character varying(4000),
    input character varying(4000),
    order_index integer NOT NULL,
    sample boolean NOT NULL,
    problem_id bigint NOT NULL
);


--
-- Name: test_case_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.test_case ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.test_case_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: topic; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.topic (
    id bigint NOT NULL,
    name character varying(255),
    order_index integer NOT NULL,
    sheet_id bigint
);


--
-- Name: topic_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.topic ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.topic_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_progress; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_progress (
    id bigint NOT NULL,
    completed_at date,
    notes character varying(2000),
    status character varying(255),
    problem_id bigint NOT NULL,
    user_id bigint NOT NULL,
    bookmarked boolean NOT NULL,
    review_due_at date,
    review_stage integer NOT NULL,
    CONSTRAINT user_progress_status_check CHECK (((status)::text = ANY ((ARRAY['TODO'::character varying, 'DONE'::character varying, 'REVISE'::character varying])::text[])))
);


--
-- Name: user_progress_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_progress ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_progress_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_user app_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_pkey PRIMARY KEY (id);


--
-- Name: contest_problem contest_problem_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contest_problem
    ADD CONSTRAINT contest_problem_pkey PRIMARY KEY (id);


--
-- Name: contest_session contest_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contest_session
    ADD CONSTRAINT contest_session_pkey PRIMARY KEY (id);


--
-- Name: problem_constraints problem_constraints_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.problem_constraints
    ADD CONSTRAINT problem_constraints_pkey PRIMARY KEY (problem_id, constraint_order);


--
-- Name: problem_examples problem_examples_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.problem_examples
    ADD CONSTRAINT problem_examples_pkey PRIMARY KEY (problem_id, example_order);


--
-- Name: problem_hints problem_hints_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.problem_hints
    ADD CONSTRAINT problem_hints_pkey PRIMARY KEY (problem_id, hint_order);


--
-- Name: problem problem_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.problem
    ADD CONSTRAINT problem_pkey PRIMARY KEY (id);


--
-- Name: sheet sheet_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sheet
    ADD CONSTRAINT sheet_pkey PRIMARY KEY (id);


--
-- Name: submission submission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.submission
    ADD CONSTRAINT submission_pkey PRIMARY KEY (id);


--
-- Name: test_case test_case_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_case
    ADD CONSTRAINT test_case_pkey PRIMARY KEY (id);


--
-- Name: topic topic_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.topic
    ADD CONSTRAINT topic_pkey PRIMARY KEY (id);


--
-- Name: app_user uk1j9d9a06i600gd43uu3km82jw; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT uk1j9d9a06i600gd43uu3km82jw UNIQUE (email);


--
-- Name: user_progress uk80hrlhmqrhuq7qd8544b304un; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_progress
    ADD CONSTRAINT uk80hrlhmqrhuq7qd8544b304un UNIQUE (user_id, problem_id);


--
-- Name: sheet ukfouhwcur4e0024gxgrknyh9a3; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sheet
    ADD CONSTRAINT ukfouhwcur4e0024gxgrknyh9a3 UNIQUE (slug);


--
-- Name: user_progress user_progress_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_progress
    ADD CONSTRAINT user_progress_pkey PRIMARY KEY (id);


--
-- Name: problem_hints fk3d4hiqi9w1oh50petfdok4tid; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.problem_hints
    ADD CONSTRAINT fk3d4hiqi9w1oh50petfdok4tid FOREIGN KEY (problem_id) REFERENCES public.problem(id);


--
-- Name: topic fk4fpsf9cb8srxbvv6rxmq3097w; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.topic
    ADD CONSTRAINT fk4fpsf9cb8srxbvv6rxmq3097w FOREIGN KEY (sheet_id) REFERENCES public.sheet(id);


--
-- Name: user_progress fk4o0atg9i3wsh4hj32r01wruaq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_progress
    ADD CONSTRAINT fk4o0atg9i3wsh4hj32r01wruaq FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: contest_problem fk8gll58cuu9lj8gwpb4my9hiwi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contest_problem
    ADD CONSTRAINT fk8gll58cuu9lj8gwpb4my9hiwi FOREIGN KEY (contest_session_id) REFERENCES public.contest_session(id);


--
-- Name: contest_problem fk9vwicr28hs8kgyj0x3skmt8uf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contest_problem
    ADD CONSTRAINT fk9vwicr28hs8kgyj0x3skmt8uf FOREIGN KEY (problem_id) REFERENCES public.problem(id);


--
-- Name: problem_constraints fkee0js867a6aroipi6pd4fhvg1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.problem_constraints
    ADD CONSTRAINT fkee0js867a6aroipi6pd4fhvg1 FOREIGN KEY (problem_id) REFERENCES public.problem(id);


--
-- Name: contest_session fkie84332pxu1j43i8go1dj8p0x; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contest_session
    ADD CONSTRAINT fkie84332pxu1j43i8go1dj8p0x FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: problem_tags fkiss624kebh6xf9q88ifretjy7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.problem_tags
    ADD CONSTRAINT fkiss624kebh6xf9q88ifretjy7 FOREIGN KEY (problem_id) REFERENCES public.problem(id);


--
-- Name: test_case fkivml84fkfpdwn2mwmt7yhjmro; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_case
    ADD CONSTRAINT fkivml84fkfpdwn2mwmt7yhjmro FOREIGN KEY (problem_id) REFERENCES public.problem(id);


--
-- Name: problem fkjwh2m0ylejp80fh5mtiv8iboc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.problem
    ADD CONSTRAINT fkjwh2m0ylejp80fh5mtiv8iboc FOREIGN KEY (topic_id) REFERENCES public.topic(id);


--
-- Name: user_progress fkpnlyy686n6d796dtvp4gyebl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_progress
    ADD CONSTRAINT fkpnlyy686n6d796dtvp4gyebl FOREIGN KEY (problem_id) REFERENCES public.problem(id);


--
-- Name: submission fkptcopqggpsnejq7vcvpxtvl9j; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.submission
    ADD CONSTRAINT fkptcopqggpsnejq7vcvpxtvl9j FOREIGN KEY (problem_id) REFERENCES public.problem(id);


--
-- Name: submission fkql0hsbof1jda7dwhs5vh59s5w; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.submission
    ADD CONSTRAINT fkql0hsbof1jda7dwhs5vh59s5w FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: problem_examples fksfonsip106wf9id88aoaq2uma; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.problem_examples
    ADD CONSTRAINT fksfonsip106wf9id88aoaq2uma FOREIGN KEY (problem_id) REFERENCES public.problem(id);


--
-- PostgreSQL database dump complete
--


